<div class="modal fade" id="categoryCreateModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog"><form method="POST" action="{{ route('admin.categories.store') }}" class="modal-content">@csrf
<div class="modal-header"><h5 class="modal-title">Create Category</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div>
<div class="modal-body"><div class="form-group"><label>Name</label><input type="text" name="name" class="form-control" required></div><div class="form-group"><label>Description</label><textarea name="description" class="form-control" rows="3"></textarea></div><div class="form-group"><label>Status</label><select name="status" class="form-control">@foreach($statuses as $status)<option value="{{ $status->value }}">{{ ucfirst($status->value) }}</option>@endforeach</select></div></div>
<div class="modal-footer"><button class="btn btn-primary">Save</button></div></form></div></div>

<div class="modal fade" id="categoryEditModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog"><form method="POST" id="categoryEditForm" class="modal-content">@csrf @method('PUT')
<div class="modal-header"><h5 class="modal-title">Update Category</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div>
<div class="modal-body"><div class="form-group"><label>Name</label><input type="text" name="name" id="edit_category_name" class="form-control" required></div><div class="form-group"><label>Description</label><textarea name="description" id="edit_category_description" class="form-control" rows="3"></textarea></div><div class="form-group"><label>Status</label><select name="status" id="edit_category_status" class="form-control">@foreach($statuses as $status)<option value="{{ $status->value }}">{{ ucfirst($status->value) }}</option>@endforeach</select></div></div>
<div class="modal-footer"><button class="btn btn-primary">Update</button></div></form></div></div>
