@extends('admin.layout.app')
@section('title', 'Clients')
@section('content')
@include('admin.partials.flash')
@include('admin.client.breadcrumb')
<div class="card"><div class="card-header admin-card-toolbar"><h3 class="card-title">Clients</h3><button class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#clientCreateModal"><i class="fas fa-plus mr-1"></i>Add Client</button></div><div class="card-body border-bottom"><form method="GET" action="{{ route('admin.clients.index') }}" class="form-row"><div class="col-md-6 mb-2"><input type="text" name="q" value="{{ request('q') }}" class="form-control" placeholder="Search client"></div><div class="col-md-2 mb-2"><button class="btn btn-info btn-sm">Apply</button></div><div class="col-md-2 mb-2"><a href="{{ route('admin.clients.index') }}" class="btn btn-secondary btn-sm">Reset</a></div></form></div><div class="card-body table-responsive p-0"><table class="table table-hover text-nowrap"><thead><tr><th>#</th><th>Name</th><th>Contact</th><th>Company</th><th>City</th><th>Action</th></tr></thead><tbody>@forelse($clients as $client)<tr><td>{{ $client->id }}</td><td>{{ $client->name }}</td><td>{{ $client->phone ?: 'N/A' }}<br><small>{{ $client->email ?: '' }}</small></td><td>{{ $client->company_name ?: 'N/A' }}</td><td>{{ $client->city ?: 'N/A' }}</td><td class="d-flex"><button class="btn btn-info btn-xs mr-1 btn-edit-client" data-action="{{ route('admin.clients.update', $client) }}" data-name="{{ $client->name }}" data-email="{{ $client->email }}" data-phone="{{ $client->phone }}" data-company_name="{{ $client->company_name }}" data-city="{{ $client->city }}" data-address="{{ $client->address }}" data-notes="{{ $client->notes }}">Edit</button><form method="POST" action="{{ route('admin.clients.destroy', $client) }}">@csrf @method('DELETE')<button class="btn btn-danger btn-xs" onclick="return confirm('Delete client?')">Delete</button></form></td></tr>@empty<tr><td colspan="6" class="text-center">No client records found.</td></tr>@endforelse</tbody></table></div><div class="card-footer">{{ $clients->links() }}</div></div>
@include('admin.client.model-create-update')
@stop
@section('css') @vite(['resources/css/app.css']) @stop
@section('js') @vite(['resources/js/app.js']) @include('admin.client.client-js') @stop
