@extends('admin.layout.app')
@section('title', 'Quotations')
@section('content')
@include('admin.partials.flash')
@include('admin.quotation.breadcrumb')
<div class="card"><div class="card-header admin-card-toolbar"><h3 class="card-title">Quotations</h3><button class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#quotationCreateModal"><i class="fas fa-plus mr-1"></i>Add Quotation</button></div><div class="card-body border-bottom"><form method="GET" action="{{ route('admin.quotations.index') }}" class="form-row"><div class="col-md-6 mb-2"><input type="text" name="q" value="{{ request('q') }}" class="form-control" placeholder="Search quotation"></div><div class="col-md-2 mb-2"><button class="btn btn-info btn-sm">Apply</button></div><div class="col-md-2 mb-2"><a href="{{ route('admin.quotations.index') }}" class="btn btn-secondary btn-sm">Reset</a></div></form></div><div class="card-body table-responsive p-0"><table class="table table-hover text-nowrap"><thead><tr><th>#</th><th>Quote #</th><th>Client</th><th>Total</th><th>Status</th><th>Valid Until</th><th>Action</th></tr></thead><tbody>@forelse($quotations as $quotation)<tr><td>{{ $quotation->id }}</td><td>{{ $quotation->quote_no }}</td><td>{{ $quotation->client?->name ?: 'N/A' }}</td><td>{{ number_format((float) $quotation->total_amount, 2) }}</td><td><span class="badge badge-info">{{ ucfirst($quotation->status) }}</span></td><td>{{ $quotation->valid_until?->format('d M Y') ?: 'N/A' }}</td><td class="d-flex"><button class="btn btn-info btn-xs mr-1 btn-edit-quotation" data-action="{{ route('admin.quotations.update', $quotation) }}" data-booking_id="{{ $quotation->booking_id }}" data-event_id="{{ $quotation->event_id }}" data-client_id="{{ $quotation->client_id }}" data-quote_no="{{ $quotation->quote_no }}" data-subtotal="{{ $quotation->subtotal }}" data-tax_amount="{{ $quotation->tax_amount }}" data-discount_amount="{{ $quotation->discount_amount }}" data-total_amount="{{ $quotation->total_amount }}" data-valid_until="{{ $quotation->valid_until?->format('Y-m-d') }}" data-status="{{ $quotation->status }}" data-notes="{{ $quotation->notes }}">Edit</button><form method="POST" action="{{ route('admin.quotations.destroy', $quotation) }}">@csrf @method('DELETE')<button class="btn btn-danger btn-xs" onclick="return confirm('Delete quotation?')">Delete</button></form></td></tr>@empty<tr><td colspan="7" class="text-center">No quotation records found.</td></tr>@endforelse</tbody></table></div><div class="card-footer">{{ $quotations->links() }}</div></div>
@include('admin.quotation.model-create-update')
@stop
@section('css') @vite(['resources/css/app.css']) @stop
@section('js') @vite(['resources/js/app.js']) @include('admin.quotation.quotation-js') @stop
