@extends('admin.layout.app')
@section('title', 'Services')
@section('content')
@include('admin.partials.flash')
@include('admin.service.breadcrumb')
<div class="card"><div class="card-header admin-card-toolbar"><h3 class="card-title">Services</h3><button class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#serviceCreateModal"><i class="fas fa-plus mr-1"></i>Add Service</button></div><div class="card-body border-bottom"><form method="GET" action="{{ route('admin.services.index') }}" class="form-row"><div class="col-md-6 mb-2"><input type="text" name="q" value="{{ request('q') }}" class="form-control" placeholder="Search service"></div><div class="col-md-2 mb-2"><button class="btn btn-info btn-sm">Apply</button></div><div class="col-md-2 mb-2"><a href="{{ route('admin.services.index') }}" class="btn btn-secondary btn-sm">Reset</a></div></form></div><div class="card-body table-responsive p-0"><table class="table table-hover text-nowrap"><thead><tr><th>#</th><th>Name</th><th>Description</th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse($services as $service)<tr><td>{{ $service->id }}</td><td>{{ $service->name }}</td><td>{{ \Illuminate\Support\Str::limit($service->description ?: 'N/A', 60) }}</td><td><span class="badge {{ $service->status ? 'badge-success' : 'badge-secondary' }}">{{ $service->status ? 'Active' : 'Inactive' }}</span></td><td class="d-flex"><button class="btn btn-info btn-xs mr-1 btn-edit-service" data-action="{{ route('admin.services.update', $service) }}" data-name="{{ $service->name }}" data-description="{{ $service->description }}" data-status="{{ $service->status ? '1' : '0' }}">Edit</button><form method="POST" action="{{ route('admin.services.destroy', $service) }}">@csrf @method('DELETE')<button class="btn btn-danger btn-xs" onclick="return confirm('Delete service?')">Delete</button></form></td></tr>@empty<tr><td colspan="5" class="text-center">No services found.</td></tr>@endforelse</tbody></table></div><div class="card-footer">{{ $services->links() }}</div></div>
@include('admin.service.model-create-update')
@stop
@section('css') @vite(['resources/css/app.css']) @stop
@section('js') @vite(['resources/js/app.js']) @include('admin.service.service-js') @stop
