@extends('admin.layout.app')
@section('title', 'Tasks')
@section('content')
@include('admin.partials.flash')
@include('admin.task.breadcrumb')
<div class="card"><div class="card-header admin-card-toolbar"><h3 class="card-title">Tasks</h3><button class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#taskCreateModal"><i class="fas fa-plus mr-1"></i>Add Task</button></div><div class="card-body border-bottom"><form method="GET" action="{{ route('admin.tasks.index') }}" class="form-row"><div class="col-md-6 mb-2"><input type="text" name="q" value="{{ request('q') }}" class="form-control" placeholder="Search task"></div><div class="col-md-2 mb-2"><button class="btn btn-info btn-sm">Apply</button></div><div class="col-md-2 mb-2"><a href="{{ route('admin.tasks.index') }}" class="btn btn-secondary btn-sm">Reset</a></div></form></div><div class="card-body table-responsive p-0"><table class="table table-hover text-nowrap"><thead><tr><th>#</th><th>Title</th><th>Event</th><th>Assignee</th><th>Priority</th><th>Status</th><th>Due</th><th>Action</th></tr></thead><tbody>@forelse($tasks as $task)<tr><td>{{ $task->id }}</td><td>{{ $task->title }}</td><td>{{ $task->event?->title ?: 'N/A' }}</td><td>{{ $task->assignee?->name ?: 'Unassigned' }}</td><td>{{ ucfirst($task->priority) }}</td><td>{{ ucfirst(str_replace('_', ' ', $task->status)) }}</td><td>{{ $task->due_at?->format('d M Y H:i') ?: 'N/A' }}</td><td class="d-flex"><button class="btn btn-info btn-xs mr-1 btn-edit-task" data-action="{{ route('admin.tasks.update', $task) }}" data-event_id="{{ $task->event_id }}" data-assigned_to="{{ $task->assigned_to }}" data-title="{{ $task->title }}" data-description="{{ $task->description }}" data-priority="{{ $task->priority }}" data-status="{{ $task->status }}" data-due_at="{{ $task->due_at?->format('Y-m-d\TH:i') }}" data-completed_at="{{ $task->completed_at?->format('Y-m-d\TH:i') }}">Edit</button><form method="POST" action="{{ route('admin.tasks.destroy', $task) }}">@csrf @method('DELETE')<button class="btn btn-danger btn-xs" onclick="return confirm('Delete task?')">Delete</button></form></td></tr>@empty<tr><td colspan="8" class="text-center">No task records found.</td></tr>@endforelse</tbody></table></div><div class="card-footer">{{ $tasks->links() }}</div></div>
@include('admin.task.model-create-update')
@stop
@section('css') @vite(['resources/css/app.css']) @stop
@section('js') @vite(['resources/js/app.js']) @include('admin.task.task-js') @stop
