@extends('admin.layout.app')
@section('title', 'Bookings')
@section('content')
@include('admin.partials.flash')
@include('admin.booking.breadcrumb')
<div class="card"><div class="card-header admin-card-toolbar"><h3 class="card-title">Bookings</h3><button class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#bookingCreateModal"><i class="fas fa-plus mr-1"></i>Add Booking</button></div><div class="card-body border-bottom"><form method="GET" action="{{ route('admin.bookings.index') }}" class="form-row"><div class="col-md-6 mb-2"><input type="text" name="q" value="{{ request('q') }}" class="form-control" placeholder="Search booking"></div><div class="col-md-2 mb-2"><button class="btn btn-info btn-sm">Apply</button></div><div class="col-md-2 mb-2"><a href="{{ route('admin.bookings.index') }}" class="btn btn-secondary btn-sm">Reset</a></div></form></div><div class="card-body table-responsive p-0"><table class="table table-hover text-nowrap"><thead><tr><th>#</th><th>Code</th><th>Client</th><th>Event</th><th>Status</th><th>Expected</th><th>Action</th></tr></thead><tbody>@forelse($bookings as $booking)<tr><td>{{ $booking->id }}</td><td>{{ $booking->booking_code }}</td><td>{{ $booking->client?->name ?: 'N/A' }}</td><td>{{ $booking->event?->title ?: 'N/A' }}</td><td><span class="badge badge-info">{{ ucfirst(str_replace('_', ' ', $booking->status)) }}</span></td><td>{{ number_format((float) $booking->expected_amount, 2) }}</td><td class="d-flex"><button class="btn btn-info btn-xs mr-1 btn-edit-booking" data-action="{{ route('admin.bookings.update', $booking) }}" data-event_id="{{ $booking->event_id }}" data-client_id="{{ $booking->client_id }}" data-booking_code="{{ $booking->booking_code }}" data-expected_amount="{{ $booking->expected_amount }}" data-status="{{ $booking->status }}" data-event_date="{{ $booking->event_date?->format('Y-m-d') }}" data-guest_count="{{ $booking->guest_count }}" data-notes="{{ $booking->notes }}">Edit</button><form method="POST" action="{{ route('admin.bookings.destroy', $booking) }}">@csrf @method('DELETE')<button class="btn btn-danger btn-xs" onclick="return confirm('Delete booking?')">Delete</button></form></td></tr>@empty<tr><td colspan="7" class="text-center">No booking records found.</td></tr>@endforelse</tbody></table></div><div class="card-footer">{{ $bookings->links() }}</div></div>
@include('admin.booking.model-create-update')
@stop
@section('css') @vite(['resources/css/app.css']) @stop
@section('js') @vite(['resources/js/app.js']) @include('admin.booking.booking-js') @stop
