<div class="modal fade" id="userCreateModal" tabindex="-1"><div class="modal-dialog"><form method="POST" action="{{ route('admin.users.store') }}" class="modal-content">@csrf
<div class="modal-header"><h5 class="modal-title">Create User</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div>
<div class="modal-body"><div class="form-group"><label>Name</label><input name="name" class="form-control" required></div><div class="form-group"><label>Email</label><input type="email" name="email" class="form-control" required></div><div class="form-group"><label>Phone</label><input name="phone" class="form-control"></div><div class="form-group"><label>Address</label><input name="address" class="form-control"></div><div class="form-group"><label>Password</label><input type="password" name="password" class="form-control" required></div><div class="form-group"><label>Roles</label><select name="roles[]" multiple class="form-control">@foreach($roles as $role)<option value="{{ $role->name }}">{{ $role->name }}</option>@endforeach</select></div><div class="form-check"><input type="checkbox" name="status" value="1" class="form-check-input" checked><label class="form-check-label">Active</label></div></div>
<div class="modal-footer"><button class="btn btn-primary">Save</button></div></form></div></div>

<div class="modal fade" id="userEditModal" tabindex="-1"><div class="modal-dialog"><form method="POST" id="userEditForm" class="modal-content">@csrf @method('PUT')
<div class="modal-header"><h5 class="modal-title">Update User</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div>
<div class="modal-body"><div class="form-group"><label>Name</label><input name="name" id="edit_user_name" class="form-control" required></div><div class="form-group"><label>Email</label><input type="email" name="email" id="edit_user_email" class="form-control" required></div><div class="form-group"><label>Phone</label><input name="phone" id="edit_user_phone" class="form-control"></div><div class="form-group"><label>Address</label><input name="address" id="edit_user_address" class="form-control"></div><div class="form-group"><label>Password (optional)</label><input type="password" name="password" class="form-control"></div><div class="form-group"><label>Roles</label><select name="roles[]" id="edit_user_roles" multiple class="form-control">@foreach($roles as $role)<option value="{{ $role->name }}">{{ $role->name }}</option>@endforeach</select></div><div class="form-check"><input type="checkbox" name="status" id="edit_user_status" value="1" class="form-check-input"><label class="form-check-label">Active</label></div></div>
<div class="modal-footer"><button class="btn btn-primary">Update</button></div></form></div></div>
